name: Auto update certificates

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: "update certificates"

env:
  ACME: ~/.acme.sh/acme.sh
  VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
  RCLONECONF: ${{ secrets.RCLONECONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Configure ACME.SH
        run: |
          curl  https://get.acme.sh | sh
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< '$RCLONECONF'
      - name: Issue & Deploy Certificates
        run: |
          mkdir -p ./ssl
          $ACME --register-account -m q211798501@hotmail.com --server zerossl
          $ACME --issue --dns dns_vultr -d moesakura.cc -d *.moesakura.cc -k ec-256
      - name: Upload & gd sync
        run: |
          rclone copyto ~/.acme.sh/moesakura.cc_ecc/fullchain.cer ali:moesakura/certificates/moesakura.cc.cer
          rclone copyto ~/.acme.sh/moesakura.cc_ecc/moesakura.cc.key ali:moesakura/certificates/moesakura.cc.key
          rclone dedupe gd:
          rclone sync gd: gdnew:
