name: FlexGet

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["FlexGet execute", "FlexGet learn"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up Rclone &Copy backend File
        run: |
          unzip rclone-linux-amd64.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
          git clone https://oauth2:$REPO_TOKEN@github.com/xusenfa/autoscriptbackend.git
          rclone copyto gdpersonal:flexget/db-config.sqlite autoscriptbackend/flexget/db-config.sqlite
      - name: file rename & Install dependencies
        run: |
          python3 autoscriptbackend/renamer.py
          python -m pip install wheel
      - name: Install & Configure FlexGet
        run: |
          pip install flexget
          cp -rl autoscriptbackend/flexget/. ~/.flexget
      - name: FlexGet execute
        if: github.event.action == 'FlexGet execute'
        run: |
          python3 autoscriptbackend/a.py
          python3 autoscriptbackend/1.py
          flexget execute
          flexget database vacuum
          flexget database clean
      - name: FlexGet learn
        if: github.event.action == 'FlexGet learn'
        run: |
          flexget execute --learn
          flexget database vacuum
          flexget database clean
      - name: Upload FlexGet database
        run: |
          python3 autoscriptbackend/upload.py
          python3 autoscriptbackend/0.py
