name: Flexget

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["Flexget execute", "Flexget learn"]
env:
  RCLONECONF: ${{ secrets.RCLONECONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p /home/runner/.config/rclone
          base64 -di > /home/runner/.config/rclone/rclone.conf <<< $RCLONECONF
      - name: Copy File
        run: |
          git clone https://oauth2:${{ secrets.REPO_TOKEN }}@github.com/xusenfa/autoscriptbackend.git
          rclone copyto ali:moesakura/flexget/db-config.sqlite autoscriptbackend/flexget/db-config.sqlite
      - name: Install FlexGet
        run: |
          pip install --upgrade wheel
          pip install --upgrade setuptools
          pip install --ignore-installed flexget
          cp -rl autoscriptbackend/flexget/. ~/.flexget
      - name: FlexGet execute
        if: github.event.action == 'Flexget execute'
        run: |
          flexget execute
          flexget database clean
          flexget database vacuum
      - name: FlexGet learn
        if: github.event.action == 'Flexget learn'
        run: |
          flexget execute --learn
          flexget database clean
          flexget database vacuum
      - name: Upload
        run: |
          rclone copyto autoscriptbackend/flexget/db-config.sqlite ali:moesakura/flexget/db-config.sqlite
