name: Cloudstorage actions

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["Rclone Actions"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}
  ALIOSSNAME: ${{ secrets.ALIOSSNAME }}
  ALIOSSPRIVATENAME: ${{ secrets.ALIOSSPRIVATENAME }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  EVENT: "Rclone Actions"
  CHECK_TASKFILENAME: "rclone schedule task"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      checkresult: ${{ steps.checkresult.outputs.test }}
    strategy:
      matrix:
        command:
          - 'rclone sync gd: odunion: -P --delete-before --delete-excluded --retries-sleep 1s --retries 10 --transfers 100 --union-min-free-space 100Gi'
          - 'rclone sync gdcy: odcy:GD备份 -P --delete-before --delete-excluded --retries-sleep 1s --retries 10 --transfers 100 --union-min-free-space 100Gi'
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      COMMAND: ${{ matrix.command }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'xusenfa/autoscriptbackend'
          path: autoscriptbackend
          token: '${{ secrets.REPO_TOKEN }}'
      - name: check
        run: |
          python3 autoscriptbackend/check.py
      - id: checkresult
        run: echo "::set-output name=test::${{ env.RUN }}"
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Rclone && Rclone actions
        run: |
          python3 -m pip install pynacl
          wget --retry-on-http-error=502,503 -t 0 -O rclone-linux-amd64.zip https://github.com/rclone/rclone/releases/download/v1.59.1/rclone-v1.59.1-linux-amd64.zip
          unzip rclone-linux-amd64.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
          rclone copyurl https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt $ALIOSSNAME/rule-providers/gfw.txt
          rclone copyurl https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt $ALIOSSNAME/rule-providers/cncidr.txt
          rclone lsf odunion:
          rclone lsf odcy:
          rclone copyto ~/.config/rclone/rclone.conf $ALIOSSPRIVATENAME/rclone.conf -P
          python3 autoscriptbackend/rcloneconfupdate.py
      - name: runjobs
        run: |
          sudo bash autoscriptbackend/killrclone.sh &
          python3 autoscriptbackend/rcloneaction.py
  call-next-task:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'xusenfa/autoscriptbackend'
          path: autoscriptbackend
          token: '${{ secrets.REPO_TOKEN }}'
      - name: call next task
        if: contains(needs.build.outputs.checkresult, 'run')
        run: |
          python3 autoscriptbackend/dispatchrclone.py
