name: Cloudstorage actions

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["rclonedaily"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}
  ALIOSSNAME: ${{ secrets.ALIOSSNAME }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'xusenfa/autoscriptbackend'
          path: autoscriptbackend
          token: '${{ secrets.REPO_TOKEN }}'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Rclone && Rclone actions
        if: github.event.action == 'rclonedaily'
        run: |
          python3 -m pip install pynacl requests
          wget --retry-on-http-error=502 -t 0 -O rclone-linux-amd64.zip https://github.com/rclone/rclone/releases/download/v1.59.1/rclone-v1.59.1-linux-amd64.zip
          unzip rclone-linux-amd64.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
          rclone copyurl https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt $ALIOSSNAME/rule-providers/gfw.txt
          rclone copyurl https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt $ALIOSSNAME/rule-providers/cncidr.txt
          rclone lsf od5t:
          rclone copyto ~/.config/rclone/rclone.conf $ALIOSSNAME/rclone.conf -P
          python3 autoscriptbackend/rcloneconfupdate.py
          rclone sync gd: od5t: -P --delete-before --exclude "cy自用勿删勿访问/" --delete-excluded
