name: Cloudstorage actions

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["rclonedaily"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rclone && Rclone actions
        if: github.event.action == 'rclonedaily'
        run: |
          wget $(curl -s https://api.github.com/repos/rclone/rclone/releases/latest | grep browser_download_url | grep linux-amd64.zip | cut -d '"' -f 4)
          unzip *.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
          sleep 1
