name: Cloudstorage actions

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["rclonedaily"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rclone && Rclone actions
        if: github.event.action == 'rclonedaily'
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF
          rclone sync gdpersonal: megaunion:gdpersonalbackup --drive-acknowledge-abuse
