name: Renamer

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["Renamer execute"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  CHECK_TASKFILENAME: "renamer"
  EVENT: "Renamer execute"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      checkresult: ${{ steps.checkresult.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'xusenfa/autoscriptbackend'
          path: autoscriptbackend
          token: '${{ secrets.REPO_TOKEN }}'
      - name: check
        run: |
          python3 autoscriptbackend/check.py
      - id: checkresult
        run: echo "::set-output name=test::${{ env.RUN }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Rclone &Copy backend File
        if: contains(env.RUN, 'run')
        run: |
          python3 autoscriptbackend/dlrclone.py
          unzip rclone-linux-amd64.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF

      - name: file rename
        if: contains(env.RUN, 'run')
        run: |
          python3 autoscriptbackend/renamer.py
  call-next-task:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "xusenfa/autoscriptbackend"
          path: autoscriptbackend
          token: "${{ secrets.REPO_TOKEN }}"
      - name: call next task
        if: contains(needs.build.outputs.checkresult, 'run')
        run: |
          python3 autoscriptbackend/dispatchrclone.py
