name: Renamer

on:
  workflow_dispatch:
  watch:
    types: [started]
  repository_dispatch:
    types: ["Renamer execute"]

env:
  RCLONECONF: ${{ secrets.RCLONECONF }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  CHECK_TASKFILENAME: "renamer"
  EVENT: "Renamer execute"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'xusenfa/autoscriptbackend'
          path: autoscriptbackend
          token: '${{ secrets.REPO_TOKEN }}'
      - name: check
        run: |
          python3 autoscriptbackend/check.py
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Rclone &Copy backend File
        if: contains(env.RUN, 'run')
        run: |
          wget --retry-on-http-error=502,503 -t 0 -O rclone-linux-amd64.zip https://github.com/rclone/rclone/releases/download/v1.59.1/rclone-v1.59.1-linux-amd64.zip
          unzip rclone-linux-amd64.zip
          sudo cp rclone*/rclone /usr/bin/rclone
          mkdir -p ~/.config/rclone
          base64 -di > ~/.config/rclone/rclone.conf <<< $RCLONECONF

      - name: file rename
        if: contains(env.RUN, 'run')
        run: |
          python3 autoscriptbackend/renamer.py
  call-next-task:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "xusenfa/autoscriptbackend"
          path: autoscriptbackend
          token: "${{ secrets.REPO_TOKEN }}"
      - name: call next task
        run: |
          python3 autoscriptbackend/dispatchrclone.py
